# Generated by Django 5.0.3 on 2024-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openAI", "0002_remove_project_description_remove_project_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project",
            field=models.JSONField(),
        ),
    ]
