# Generated by Django 5.0.3 on 2024-03-14 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openAI", "0002_alter_project_resources_alter_project_technologies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="owner",
            new_name="author",
        ),
    ]
